---

dependencies: []

galaxy_info:
  author: javaguirre
  description: Manage Event driven Chat (installation, configuration)
  license: MIT
  min_ansible_version: 1.6
  platforms:
    - name: Ubuntu
  versions:
    - all
  categories:
    - web