---

chat_path: /home/{{ ansible_ssh_user }}/chat

supervisor_enabled: yes

supervisor_tasks:
  - name: chat
    directory: '{{ chat_path }}'
    command: '{{ chat_path }}/.venv/bin/python app.py'
    user: '{{ ansible_ssh_user }}'
    stdout_logfile: /var/log/supervisor/chat.log
    stderr_logfile: /var/log/supervisor/chat.error.log
    autostart: true
    autorestart: true